version: "3.7"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - simapd-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      - pg
    networks:
      - simapd-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    depends_on:
      - pg
    networks:
      - simapd-network

volumes:
  postgres_data:

networks:
  simapd-network:
    driver: bridge
